services:
  postgres-falcao:
    image: postgres:15.3-alpine
    container_name: postgres-falcao
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  pgadmin-falcao:
    image: dpage/pgadmin4:latest
    container_name: pgadmin-falcao
    restart: always
    depends_on:
      - postgres-falcao
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8080:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    user: "0"

networks:
  default:
    name: local-network
